### ISSUE TITLE
move_base node is not accepting relay topic

### ISSUE THREAD

**Issue by sunil1349** [fkie/multimaster_fkie#102]
i am using two identical robots and one base station,
move_base is running in both robots ,i given relay topic in both robots as following
`<node name="master_sync" pkg="master_sync_fkie" type="master_sync" output="screen">
	<rosparam param="ignore_hosts">[]</rosparam>	
	<rosparam param="sync_hosts">["lmrobot-Alpha","mrobot2-desktop"]</rosparam>
	
	<rosparam param="ignore_topics">['/cmd_vel_move_base', '/initialpose', '/master_discovery/changes', '/master_discovery/linkstats', '/odom', '/particlecloud', '/rmr/rt_motion_vel', '/rosout' , '/rosout_agg', '/scan', '/tf', '/tf_static']</rosparam>
	<rosparam param="sync_topics">['/map', 'robot0/move_base/goal', '/robot0/amcl_pose']</rosparam>
	
</node>`
but in base station it is not showing any move_base from both robots

**Comment by atiderko** [comment]
did you run `master_discovery` on all robots and base station? And on base station `master_sync`? Which filter are you configured for `master_sync`? Is this topic or node filtered by your configuration?

Is the topic name of `relay` and `move_base` equal?

**Comment by sunil1349** [comment]
yes i do run master_discovery on all robots and base station 
the thing is i used relay topic for amcl_pose in both robots is working 
but for move_base it is not working

**Comment by atiderko** [comment]
Is /robot0/move_base a topic name or node name? I mean it should be a topic name.

**Comment by sunil1349** [comment]
yes it is node name but i used relay for list of topics under move_base example.
`<rosparam param="sync_topics">['/map', 'robot0/move_base/goal', '/robot0/amcl_pose']</rosparam>`
it is not working for it even i given relay for particular topic

**Comment by atiderko** [comment]
in your configuration only one move_base topic should be synchronized: `robot0/move_base/goal`. All other are ignored and on the base station not visible. But you should add `/` in the front of `robot0/move_base/goal`!

**Comment by atiderko** [comment]
I hope this issue was solved, please reopen if not!
