### ISSUE TITLE
Problem with catkin_make

### ISSUE THREAD

**Issue by onionsflying** [fkie/multimaster_fkie#111]
* Ubuntu version: Ubuntu 16.04
* ROS Workstation version: Kinetic

Hi, I built the latest packages with `catkin build` and `catkin_make`. `catkin build` worked well. But some errors came out when I used `catkin_make`.
![catkin_make](https://user-images.githubusercontent.com/19217655/62844649-4577cf80-bcf5-11e9-9bb6-cfe0de1f6dfa.png)

**Comment by atiderko** [comment]
@onionsflying thank you for reporting!

It should be fixed now!
