### ISSUE TITLE
Mismatching message versions are not producing errors

### ISSUE THREAD

**Issue by beetleskin** [fkie/multimaster_fkie#114]
I ran multimaster on two machines and connected publisher and subscriber across. The publisher was started on machine A and publishing was confirmed on machine A. On machine B, however, `rostopic echo` showed nothing.
It took me a while to figure out, that the message version was different for the machines. 

With a single roscore, one would receive an error á la 

`[ERROR]: [Client [/node_a] wants topic /foo/bar to have datatype/md5sum [foo_bar_msgs/Bar/789e86cf5605527579fc43fbc56f64fd], but our version has [foo_bar_msgs/Bar/4f19452d19db3698175d210d370d7d9d]. Dropping connection.
`

It would be great, if we'd get a similar message when running multimaster.

**Comment by atiderko** [comment]
Hi @beetleskin 

I wonder why your publisher does not shows warning message on connect with changed topic type.
The type check is done by ROS publisher and is independent from multimaster.
Multimaster (un)register publisher and subscriber by ROS Master and creates no connections. The topic connection process is done by ROS in the same manner if you use ROS single core.

The additional check for md5sum in multimaster could be a nice feature. I will check how many effort it would be to implement it.

**Comment by atiderko** [comment]
I added check and warning to different checksum with new commit 11b1690
. I hope it will improve the detection of this kind of problems.

**Comment by beetleskin** [comment]
> I wonder why your publisher does not shows warning message on connect with changed topic type.

Uh, I only checked the subscriber to be honest, i.e. `rostopic echo`

> I added check and warning to different checksum with new commit
Great! Thanks for the super fast response!
