### ISSUE TITLE
How to connect two computers

### ISSUE THREAD

**Issue by lijian636** [fkie/multimaster_fkie#133]
How to connect two computers? I always have problems. Can you tell me how to do it

**Comment by atiderko** [comment]
did you tried these steps:
http://wiki.ros.org/multimaster_fkie/Tutorials/Setup%20a%20ROS%20master%20synchronization

If so can you tell me which problems you have, please.

**Comment by lijian636** [comment]
When I open the interface on one host, I start the discovery node on another host. At this time, when the interface detects the discovery node, the interface will automatically close and the terminal will output the abandoned. I want to know what to do

**Comment by atiderko** [comment]
Can you provide me some log outputs (of master_discovery, master_sync,
node_manager) or screenshots, please.

What is an interface? Is it a terminal?

Am Mi., 29. Juli 2020 um 03:01 Uhr schrieb lijian636 <
notifications@github.com>:
