### ISSUE TITLE
Connection between desktop computer and raspberry

### ISSUE THREAD

**Issue by OtaviodaCruz** [fkie/multimaster_fkie#136]
Hello everyone. I'm using fkie multimaster for 2 machines, a **desktop computer and a raspberry.**

To test whether the communication used the basis of the turtlesim example. Basically I started a turtlesim node in the **rasp**. So, when running `rostopic list` on the **desktop computer** I get the following result:
```
/master_discovery/changes
/master_discovery/linkstats
/rosout
/rosout_agg
/turtle1/cmd_vel
/turtle1/color_sensor
/turtle1/pose
```
This seems to suggest that communication is working. The problem is when I try to control the turtle's movements on the **desktop computer**. Using something like:

`rosrun turtlesim turtle_teleop_key`
or
`rostopic pub /turtle1/cmd_vel geometry_msgs/Twist -r 1 -- '[2.0, 0.0, 0.0]' '[0.0, 0.0, 1.8]'`

When trying to execute these commands to control the turtlesim node created in rasp nothing happens: /
I hoped I could control the turtle. Anyway, my question is: is what I am trying to do possible? Or is it off limits to fkie?

**Comment by atiderko** [comment]
Hi OtaviodaCruz,

your scenario is what multimaster_fkie was developed for!
But there are some limitations due to ROS communication establishement between topics. Internally ROS uses hostnames and connects using these names. Please test if names are resolved to the right IP addresses.

Please set also the ROS_MASTER_URI to hostsname, e.g. export ROS_MASTER_URI=http://rasp:11311 and not to localhost, see:
http://wiki.ros.org/ROS/EnvironmentVariables#ROS_MASTER_URI

You can try to start 'node_manager'. Some of the problems could be shown in the GUI.

**Comment by OtaviodaCruz** [comment]
Thanks for the answer.
In this case, before I need to configure my etc / host file for the IP and names of my computers, right?
I will try as you indicated. Do you have any explanation about the need to enter a host name? Because in my mind it was supposed to work with localhost too

**Comment by atiderko** [comment]
Multiamster FKIE does not need the hostname in ROS_MASTER_URI and in most cases it works also with `localhost`. But if you have some troubles you should set it to the name of localhost, see official explanation: `Great care should be taken when using localhost, as that can lead to unintended behaviors with remotely launched nodes. `

Since ROS uses the hostname to communicate, you need to enter all hosts with ROS into your `/etc/host`.

You can also try to set `ROS_IP`, but it has also limitation since it binds to specified device. If this device is WiFi and you lost the connection the local nodes can't communicate, too.

**Comment by OtaviodaCruz** [comment]
Got it, it's more of a precaution.

I will describe my unsuccessful test below.
Well, first I changed the hosts files, for each computer (desktop and raspberry)
![Deepin Screenshot_selecionar área_20200912001428](https://user-images.githubusercontent.com/30325754/92985870-f6b6df00-f48c-11ea-8540-22086de1775a.png)

Firt I executed in desktop computer:

`export ROS_MASTER_URI=http://pc1:11311`

And in my rapsberry:

`export ROS_MASTER_URI=http://pc2:11311`

Then, I executed the following commands on each machine
```
roscore
rorun master_discovery_fkie maste_discovery _mcast_group: = 224.0.0.251
rosrun master_sync_fkie master_sync
```
So, in the rasp I do:

`- rosrun turtlesim turtlesim_node`

As expected, a window with a turtle in the middle appears. 

![Deepin Screenshot_selecionar área_20200912003739](https://user-images.githubusercontent.com/30325754/92986335-3b904500-f490-11ea-8b25-76ce332fddbc.png)

Next, I make the following command on the desktop computer:

`- rostopic list`

The result is:

```
/master_discovery/changes

/master_discovery/linkstats

/rosout

/rosout_agg

/turtle1/cmd_vel

/turtle1/color_sensor

/turtle1/pose
```
Apparently fkie is working. The problem is when I try to control the turtle's movements on the desktop computer. Using something like:

`rosrun turtlesim turtle_teleop_key`

or

`rostopic pub /turtle1/cmd_vel geometry_msgs/Twist -r 1 -- '[2.0, 0.0, 0.0]' '[0.0, 0.0, 1.8]'`

But if I execute the command on the rasp (where the turtle node was started) it works perfectly.  
The strangest thing is that when executing the command rqt_graph everything seems to be working perfectly.

![Deepin Screenshot_selecionar área_20200831232623](https://user-images.githubusercontent.com/30325754/92986201-88275080-f48f-11ea-8dcf-70bda596a3c8.png)


I use melodic, in my desktop computer with ubuntu 18.04 and my rasp ubuntu mate 18.04.

**Comment by atiderko** [comment]
That is very strange behavior. If you run
```rostopic pub /turtle1/cmd_vel geometry_msgs/Twist -r 1 -- '[2.0, 0.0, 0.0]' '[0.0, 0.0, 1.8]'```
and nothing happens it could be a problem to  establish a connection between turtlesim and rostopic. This should be done by ROS itself. Master_sync registers only the connection information in roscore. And that seems to work ;) unless they're wrong...

Are there some wranings in the output of `master_dycovery` or `master_sync`?

Did you checked the info of the /turtlesim node? It should look like:
```
robot@control:~$ rosnode info /turtlesim 
--------------------------------------------------------------------------------
Node [/turtlesim]
Publications: 
 * /turtle1/color_sensor [turtlesim/Color]
 * /turtle1/pose [turtlesim/Pose]

Subscriptions: 
 * /turtle1/cmd_vel [geometry_msgs/Twist]

Services: 
 * /clear
 * /kill
 * /reset
 * /spawn
 * /turtle1/set_pen
 * /turtle1/teleport_absolute
 * /turtle1/teleport_relative


contacting node http://tiderko5:44023/ ...
Pid: 3559
Connections:
 * topic: /rosout
    * to: /rosout
    * direction: outbound (43661 - 192.168.178.104:54332) [27]           <--- local connection
    * transport: TCPROS
 * topic: /turtle1/cmd_vel
    * to: /rostopic_20020_1599895127680 (http://control:35131/)          <--- remote connection
    * direction: inbound (54398 - ros2:42761) [33]
    * transport: TCPROS
```
And your `rqt_graph` looks like (except node_manager, node_manager_daemon): 
![Screenshot_2020-09-12_09-23-50](https://user-images.githubusercontent.com/1736543/92990494-3d342a00-f4dd-11ea-8ce5-a5c3dcb628d2.png)

Did you tried `roswtf`?

**Comment by OtaviodaCruz** [comment]
There are no errors in the master_dycoveryor master_sync output. Just a few WARN:

![Deepin Screenshot_selecionar área_20200913151721](https://user-images.githubusercontent.com/30325754/93025452-6edbec80-f5d4-11ea-823c-3aa45c9b7630.png)

I have now tried to check the node information. Finally I see an error impression

![Deepin Screenshot_selecionar área_20200913152024](https://user-images.githubusercontent.com/30325754/93025492-da25be80-f5d4-11ea-98b9-ec4b622454bd.png)

It prints the information but prints an error "ERROR: Communication with node [http: // otavio-desktop: 46633 /] failed!". I thought it was strange, if he has communication problems, how can he press the information?

When I start the turtle node in RASP, I have

![Deepin Screenshot_selecionar área_20200913150141 (6)](https://user-images.githubusercontent.com/30325754/93025570-4f918f00-f5d5-11ea-8023-11939552fd4e.png)

Again it looks like the communication was successful, since it detected the turtle node.
And when I try to control the turtle's movements on my desktop computer I have

![Deepin Screenshot_selecionar área_20200913150242](https://user-images.githubusercontent.com/30325754/93025578-56200680-f5d5-11ea-9774-fe0bbc4f4a54.png)

In this image, it does not appear that the desktop computer is accessing / publishing on the turtlesim node created in RASP.

I'm sorry, I didn't know roswtf, I'm relatively new to ROS. When executing, I got

![Deepin Screenshot_selecionar área_20200913153638](https://user-images.githubusercontent.com/30325754/93025749-11956a80-f5d7-11ea-8cc5-ac9143d9b578.png)

**Comment by OtaviodaCruz** [comment]
When I run
`rostopic pub / turtle1 / cmd_vel geometry_msgs / Twist -r 1 - '[2.0, 0.0, 0.0]' '[0.0, 0.0, 1.8]'`
I have roswtf
![Deepin Screenshot_selecionar área_20200913154428](https://user-images.githubusercontent.com/30325754/93025892-363e1200-f5d8-11ea-8d3a-6e0ee5ff3031.png)

So sad :/
Communication is really not working.

**Comment by atiderko** [comment]
can you ping the `otavio-to-be-filled-by-e-o-m` from your desktop PC?

The warning in `master_discovery` is in your case an error because it can not resolve this name.

**Comment by OtaviodaCruz** [comment]
Good news, it worked, before describing what I did I will answer the last message.

Yes, I can

![Deepin Screenshot_selecionar área_20200914142913](https://user-images.githubusercontent.com/30325754/93118784-2d604580-f697-11ea-874b-a504f9b1f9b8.png)


I realized that even using

`export ROS_MASTER_URI=http://pc1:11311`
and
`export ROS_MASTER_URI=http://pc2:11311`

my roscore still appeared as otavio-desktop (PI) and  otavio-To-be-filled-by-O-E-M (Desktop computer), look

![Deepin Screenshot_selecionar área_20200914142740](https://user-images.githubusercontent.com/30325754/93119127-a65f9d00-f697-11ea-8b09-45a65108de3a.png)

In addition there is the Warning that you mentioned yourself.
So I replaced pc1 and pc2 of my hosts file with

192.168.100.28  otavio-desktop
192.168.100.5   otavio-To-be-filled-by-O-E-M

After that everything worked perfectly.

I still don't know why it didn't work as pc1 and pc2, there must be some configuration that is making my roscore always run like otavio-desktop and  otavio-To-be-filled-by-O-E-M.

Thanks a lot for the help :)

**Comment by atiderko** [comment]
This are good new :-)

_I still don't know why it didn't work as pc1 and pc2, there must be some configuration that is making my roscore always run like otavio-desktop and otavio-To-be-filled-by-O-E-M._
This is default behavior of ROS. You can overwrite it by setting ROS_HOSTNAME e.g `export ROS_HOSTNAME=pc1`
I also did not realized that you used different names for the same host.
But all's well that ends well!
