### ISSUE TITLE
Problems with online testing of two computers

### ISSUE THREAD

**Issue by wangmengjian** [fkie/multimaster_fkie#137]
Two computers are connected to test the turtle example, the following problems occur, how can I solve it?
![2020-09-18 14-36-49屏幕截图](https://user-images.githubusercontent.com/43922432/93564547-73314c80-f9bc-11ea-8be2-16904006b7e5.png)

**Comment by atiderko** [comment]
if I understand correctly, you want to connect the two computers via IOP.
- Red ERROR: You should run `iopnodemanager` on both computer.
- The warning about: set ROS_MASTER_URI to local computer names and start `master_discovery` using **start**-Button in Node Manager

**Comment by atiderko** [comment]
please reopen, if the problem still occurs
