### ISSUE TITLE
Adjust the number of launch files shown in the launch_files tab

### ISSUE THREAD

**Issue by weixuanzhang** [fkie/multimaster_fkie#141]
Would it be possible to adjust the number of launch files shown in the launch_files tab? Consider the following example:
![Screenshot from 2020-10-29 15-09-37](https://user-images.githubusercontent.com/8019238/97585114-108a9200-19f9-11eb-9498-8959cf004909.png)
The most recent five launch files are shown. However, I usually have around 10 launch files (and different combinations of them) that I regularly use. Would it be possible to show more? Otherwise, I always have to manually dig into the package launch files and this is time-consuming. Thank you very much!

**Comment by atiderko** [comment]
you can change the `Launch history length` parameter in the `Settings` tab
http://fkie.github.io/multimaster_fkie/chapter_usage/settings.html

**Comment by weixuanzhang** [comment]
Thank you very much! I will close the issue.
