### ISSUE TITLE
ROS noetic support

### ISSUE THREAD

**Issue by b-reich** [fkie/multimaster_fkie#143]
Is it planned to support ros noetic?

**Comment by atiderko** [comment]
Please checkout 'noetic-devel'

**Comment by julianraheema** [comment]
Is this one going to be in ros-noetic release. So we can get it as `apt install ros-noetic-multimaster-fkie and apt install ros-noetic-master-sync-fkie`?

**Comment by atiderko** [comment]
there is already a noetic release, but only with `ros-noetic-fkie-master-sync` and `ros-noetic-fkie-master-discovery` working
