### ISSUE TITLE
master_discovery memory leak

### ISSUE THREAD

**Issue by amilcarlucas** [fkie/multimaster_fkie#148]
I'm using the latest master version compiled on NVidia Jetson TX2, TX2i and NX.
All three boards run on Ubuntu 18.04 LTS.

The longer the master_discovery service runs the more memory it needs.
I suspect it has a memory leak!

**Comment by atiderko** [comment]
I run some tests with five ROS-Master's (five `master_discovery`, five `master_sync` and one `node_manager`) on Ubuntu 18.04.

I record the memory usage with `psrecord`.

With no changes on ROS-Master the memory usage increases slowly (almost an hour) until an upper limit (60MB)
![md_no_changes_in_ros_master](https://user-images.githubusercontent.com/1736543/102370347-3e359580-3fbd-11eb-82c8-bd517e4c9e75.png)

With a ROS-Node stop/start every 5 seconds the limit of 60 MB is reached faster and stay at this level.
![md_new_nodes_every_app_5s](https://user-images.githubusercontent.com/1736543/102370648-9a98b500-3fbd-11eb-9e31-951d45a876ff.png)

I don't know exactly what the reason for the increase is at the beginning and whether it can be fixed at all.

**Comment by amilcarlucas** [comment]
I now upgraded to Ubuntu 20.04 LTS and ROS noetic
After a couple of days it increases from 40MiB to 140MiB

**Comment by amilcarlucas** [comment]
Any progress on this?
Please re-open it.
