### ISSUE TITLE
master synchronization always failed

### ISSUE THREAD

**Issue by nuriozalp** [fkie/multimaster_fkie#15]
When conneciton time out your master synchronization kill itself. But Master Discovery continue to wkorking.  Can you restart your master synchronization when it take a message from master discovery. Maybe you can write a subscribe to discovery node or when it restart to take any message from discovery it can restart master synchronization again. We use your project at our project. İf ı know phyton well i would do it myself.

**Comment by atiderko** [comment]
Do you have still problems with synchronization?
