### ISSUE TITLE
Can two computers run two Gazebo and two RVIZ after running multimaster_fkie? 

### ISSUE THREAD

**Issue by 15993217652** [fkie/multimaster_fkie#154]
Can two computers run two Gazebo and two RVIZ after running multimaster_fkie?  
Why is it that when one computer runs Gazebo and another runs Gazebo, it is killed

**Comment by atiderko** [comment]
Multimaster synchronizes several `roscore's` without changing the names of the nodes and topics. The advantage is that the launch files for a single system and multi-core system do not have to be changed.
However, if two nodes with the same name are started in the system, these nodes will be terminated.
This is ROS behaviour!

To prevent this, the same nodes must be started in different namespaces.
Or you add these nodes to the `master_sync` ignore list.

**Comment by 15993217652** [comment]
Thank you very much for your reply. I will try again

**Comment by 15993217652** [comment]
Now, I can run two Gazebo on two computers, but I want to subscribe to topics for neglected nodes. Is that allowed

**Comment by atiderko** [comment]
if you put the gazebo in a different namespace, you can subscribe to topics. If they're on the ignore list, then not.

**Comment by 15993217652** [comment]
Thank you very much for your reply. Now I have understood everything

**Comment by atiderko** [comment]
you are welcome! I am sorry for the late reply
