### ISSUE TITLE
ssh

### ISSUE THREAD

**Issue by lijian636** [fkie/multimaster_fkie#157]
When I click on the ssh connection remote host function on the interface, it prompts robot@sy's password:, but I make sure that my password is entered correctly, but I will always be prompted to re-enter it. I don’t know what to do. If you know why, please let me know I am grateful.

**Comment by atiderko** [comment]
In most cases the user does not exists or the password is wrong.

Which function of the node manager did you use? Are errors or warnings printed in the terminal where you launched the node manager?

**Comment by atiderko** [comment]
I assume it was solved, please reopen if not!
