### ISSUE TITLE
Error when trying to publish std_msgs/Empty topic

### ISSUE THREAD

**Issue by ipa-lth** [fkie/multimaster_fkie#17]
Something goes wrong when I try to publish an Empty msg of the type std_msgs/Empty from the node_manager gui/ topic tab

**Comment by roehling** [comment]
[WARN] rosout: Publish topic '/empty' failed: 'std_msgs/Empty'
    [DEBUG] rosout: MASTERINFO from roehling (http://roehling:11311/) received
    Traceback (most recent call last):
      File "/home/roehling/ros/src/multimaster_fkie/node_manager_fkie/src/node_manager_fkie/master_view_proxy.py", line 2301, in _start_publisher
        topic_params = self._rem_empty_lists(params[topic_type])
    KeyError: 'std_msgs/Empty'

**Comment by atiderko** [comment]
I fixed it.
