### ISSUE TITLE
Topic appearing on rostopic list but not publishing to remote node

### ISSUE THREAD

**Issue by MitchGaleaAbyss** [fkie/multimaster_fkie#176]
System consists of 3 computers:
A: 
- robot
- running ros master on 192.168.*.4
- connected to B via ethernet, IP: 192.168.*.4

B:
- laptop
- connected to A via ethernet, IP: 192.168.*.1
- running master_discovery on with ROS_MASTER_URI 192.168.*.4 sourced
- running ros master on 10.137.*.1
- connected to B on separate wifi, IP: 10.137.*.1
- running master_discovery on with ROS_MASTER_URI 10.137.*.1 sourced
- ROS network with master 10.137.*.1 can echo topics published by A on separate ROS Network

C:
- laptop
- connected to B via wifi, IP: 10.137.*.2
- can see topic published by A but cannot echo the topic

I have tried with enabled sync_remote_nodes and this has not helped
Any suggestions

**Comment by atiderko** [comment]
The multimaster package __only__ synchronizes the entries in the ROS master. The connection between the topics is established by the ROS system itself.
So if you can't ping A from the C, ROS nodes won't be able to connect either.
