### ISSUE TITLE
issue about tf update

### ISSUE THREAD

**Issue by hsx479** [fkie/multimaster_fkie#177]
Hello, when I use multimaster_fkie to run multi roscores on two computers and use rviz , there is some problem about the tf:
`Transform `[sender=unknown_publisher]`
`For frame [base_scan]: No transform to fixed frame [map]. TF error: [Lookup would require extrapolation into the future. Requested time 1655363434.854527810 but the latest data is at time 1655363416.292566976, when looking up transform from frame [base_scan] to frame [map]]`
**And the " requested time" is constantly updated.**
This problem does not arise if I just use one computer and don't use multimaster_fkie.
Is there anything in multimaster_fkie may cause this problem?

**Comment by atiderko** [comment]
Sorry for the late reply!
The time of the two hosts is not in sync. You need to use an NPT client, e.g. chrony, and sync the time.
