### ISSUE TITLE
Loading .nmprofile configuration into node_manager GUI

### ISSUE THREAD

**Issue by jakebonney10** [fkie/multimaster_fkie#179]
I'm having trouble loading the node manager profile that I stored from the launch dock. Its currently saved to my desktop. I haven't been able to find any support on this in the wiki/manual. Is there an easy way to do this from the node_manager gui? 

In an ideal world I envision running node_manager with its profile specified from a launch file, similar to how an rviz config can be specified using args. Is there functionality to do this?

**Comment by atiderko** [comment]
sorry for long delay!

nmprofile stores running multimaster nodes, loaded launch files and running nodes. So you can  restore the running state by loading the file from launch dock or with start of node_manager by `node_manager -f name.nmprofile`.

This feature is experimental and was not tested for long time :-/ 
I fixed now some issues with loading the nmprofiles.
