### ISSUE TITLE
Using IP address instead of hostname to sync masters

### ISSUE THREAD

**Issue by mariocorsanici** [fkie/multimaster_fkie#183]
Hello,

I am trying to run multimaster in a docker container and I want to automate the sync procedure between the masters without modifying the /etc/hosts file, since it's a system file. Is it possible to use the IP address instead of the hostname to communicate with the masters?

**Comment by atiderko** [comment]
Hi,
you have to set the ROS_IP environment variable before starting the roscore and other ROS nodes.
This should be enough.

**Comment by mariocorsanici** [comment]
Thank you so much, it worked.
