### ISSUE TITLE
Feed args to autostart launch files

### ISSUE THREAD

**Issue by 010101101101** [fkie/multimaster_fkie#188]
I am running multiple launch files with

```
<node pkg="fkie_node_manager_daemon"
           type="node_manager_daemon"
           name="node_manager_daemon"
           args="--autostart '$(arg _autostart_launch_files)'"/>
```

All these launch files require a robot_namespace arg to be set. How do I update the above code to feed the robot_namespace arg to all launch files?

**Comment by atiderko** [comment]
Setting arguments at autostart is not supported by the daemon.

You can create another launch file that includes all launch files and sets required arguments. The new launch file does not necessarily have to be in a ROS package.

**Comment by atiderko** [comment]
Please reopen if the problem persists.
