### ISSUE TITLE
Dependency on python-qt

### ISSUE THREAD

**Issue by fmina** [fkie/multimaster_fkie#22]
Hi, 
When we start to discover the master on remote host we get python error stating that the python-qt-buinding module is not existing. However we have limited storage on the robot and we want to avoid installing python-qt. Is the dependency on python-qt necessary even on the robot?
We tried to start only master-discovery on the robot and the node_manager discovered the robot, but same issue happens when we start a node for instance.

Thank you

**Comment by atiderko** [comment]
Hi,
to run nodes on remote hosts from node_manager we use scripts in scripts folder of node_manager package. These scripts use the code of node_manager to simplify the maintenance. It is possible to extract the code, so it does not need the python-qt. I will try to create this script, but next week.
Regards

**Comment by atiderko** [comment]
hi,
I created a backup script, which work without qt bindings. It was not a lot of changes :-)
Try it out, it is in master branch.

**Comment by fmina** [comment]
Thanks, I will try it and let you know :)

**Comment by fmina** [comment]
Works perfectly, please close the issue. 
Thanks :+1:

**Comment by atiderko** [comment]
:+1:
