### ISSUE TITLE
master monitor throws errors when services disappear

### ISSUE THREAD

**Issue by garyservin** [fkie/multimaster_fkie#30]
Hello!

We have a setup with two masters running and communicating fine until one service disappear from one of the masters and we get the following error:
```

[ERROR] [/move_base] [1447105026.919308544, 46.419000000]: received a tcpros connection for a nonexistent service [/test_service].
[WARN] [WallTime: 1447105026.935162] [46.429000] MasterMonitor[/test_service]: can't get service type: Traceback (most recent call last):
  File "/home/gary/multimsater_ws/install/lib/python2.7/dist-packages/master_discovery_fkie/master_monitor.py", line 346, in _getServiceInfo
    self.__new_master_state.getService(service).type = stype['type']
KeyError: 'type'
```

We get the same error with multimaster debs and when buildt from source.

Any ideas on this?
Thanks

**Comment by atiderko** [comment]
Hi,

this warning is printed on connection problems to a registered service (by roscore). In this case the type of this service will not published to remote `master_sync`. The printed warning helps to find the problem if the service is not registered on remote ROSMaster.

But other functions of the `master_discovery` or `master_sync` should not be affected.

So you can search for problem, why the service disappear ;-)

Regards,
Alex
