### ISSUE TITLE
Progress Job Error

### ISSUE THREAD

**Issue by thelme** [fkie/multimaster_fkie#35]
Hello !

When I try to launch some node in an other machine (connected and syncronised), I have a "Progress Job Error":

> Traceback (most recent call last):
>   File "/opt/ros/indigo/lib/python2.7/dist-packages/node_manager_fkie/progress_queue.py", line 276, in run
>     self._target(*self._args)
> TypeError: runNode() takes exactly 2 arguments (4 given)

Do you have an idea ?

**Comment by atiderko** [comment]
Hi,

which version did you use? Perhaps this error already fixed by this commit 299192daf8b0d2ed3ce633f6aa775a76b8895792

**Comment by thelme** [comment]
endeed, thanck !
