### ISSUE TITLE
Request for a release tag

### ISSUE THREAD

**Issue by deng02** [fkie/multimaster_fkie#41]
We've been testing the latest version and would like to include the current set of commits in our next release. In particular we are interested in the fix that addresses the case where the masteruriaddr is None as this has shown up in our logs.  If possible we're like to tag a release for indigo-devel so we can get that in.  Thanks.

**Comment by atiderko** [comment]
I created a release tag 0.5.5 and generated a bloom-release [indigo status](http://repositories.ros.org/status_page/ros_indigo_default.html?q=fkie)

**Comment by deng02** [comment]
That's perfect, thanks!
