### ISSUE TITLE
Incompatible ssh peer 

### ISSUE THREAD

**Issue by thelme** [fkie/multimaster_fkie#45]
I try to connect on a raspberry zero with indigo and "Raspbian GNU/Linux 8.0 (jessie)"

but : 

> failed : Incompatible ssh peer (no acceptable kex algorithm)

**Comment by atiderko** [comment]
it seems to bee a [paramiko issue](https://github.com/paramiko/paramiko/issues/423).

Please try to fix it using the proposed solutions on [stackoverflow](http://stackoverflow.com/questions/7286929/paramiko-incompatible-ssh-peer-no-acceptable-kex-algorithm)
