### ISSUE TITLE
Why ROS package still missing?

### ISSUE THREAD

**Issue by Sr4l** [fkie/multimaster_fkie#47]
Hey,

I am not familiar with the packing / approval process of ROS so my question: Why is the package of multimasters / node_manger (ros-kinetic-node-manager-fkie) for kinetic still missing?

Can I help somehow?

**Comment by atiderko** [comment]
Hi,

it is currently released [ros-repos](http://repositories.ros.org/status_page/ros_kinetic_default.html?q=fkie). It should be available after the next package sync.

**Comment by Sr4l** [comment]
Thanks for the explanation and for the shadow repository tip.
