### ISSUE TITLE
No module named editor

### ISSUE THREAD

**Issue by jeffeb3** [fkie/multimaster_fkie#49]
I'm not sure when this broke, but I can't run node_manager on my machine any more. It just prints:

    No module named editor

And then exits. This is ubuntu 14.04, and I have ros-indigo-node-manager-fkie installed. I tried reinstalling some things, and even did `pip install python-editor`, but no dice. Any tips on what might be broken?

**Comment by atiderko** [comment]
Hi,

oh, after the editor module was added, the install script was not updated :-/. I will fix it as soon as possible. 

In the meantime you can clone it from the github and use it in your ros workspace or copy the `multimaster_fkie/node_manager_fkie/src/node_manager_fkie/editor` folder to `/opt/ros/indigo/lib/python2.7/dist-packages/node_manager_fkie/editor`

regards
