### ISSUE TITLE
Echo window not working in 0.7.6

### ISSUE THREAD

**Issue by j3sq** [fkie/multimaster_fkie#65]
Clicking "echo" next to a topic fails to open the "echo" window and log the following message:
[Errno 2] No such file or directory: 'path/to/catkin_ws/install/lib/python2.7/dist-packages/node_manager_fkie/EchoDialog.ui'

This is caused by a missing install line  for "EchoDialog.ui" in  "multimaster_fkie/node_manager_fkie/CMakeLists.txt"

**Comment by atiderko** [comment]
@j3sq thank you for reporting!
I fixed this issue and created a new release 0.7.7
