### ISSUE TITLE
Dynamic Reconfigure

### ISSUE THREAD

**Issue by akifh** [fkie/multimaster_fkie#67]
Hello @atiderko ,

Thank you for the great effort to develop and maintain this package. What I want to ask that, do you have dynamic reconfigure feature in future plans? Especially for master_sync to configure parameters like ignore_hosts, sync_hosts in runtime.

Best

**Comment by atiderko** [comment]
Hello @akifh,

Thank you for the positive feedback!
Currently there are no plans to add dynamic reconfigure. Unfortunately, I have also no time to implement this feature in a near future. But I accept pull requests ;-)

regards

**Comment by akifh** [comment]
I'll look into it, hopefully :) Thank you for the reply.

Best
