### ISSUE TITLE
Sharing pose data via multimaster between three robots

### ISSUE THREAD

**Issue by sjoshi30** [fkie/multimaster_fkie#72]
I want to run AMCL package on three different robots(each robot has laptop with ros running on it) and share the pose data via multimaster_fkie. When we sync the three laptops, the bandwidth decreases significantly. Is there any solution for this ?

**Comment by atiderko** [comment]
Hi,

you can add filter to exclude some topics from synchronization. E.g. /tf topic is a candidate. Add follow parameter to *master_sync* node:
``` <rosparam param="ignore_topics">[/tf]</rosparam>```

For more filter options see [master_sync.launch](https://github.com/fkie/multimaster_fkie/blob/master/master_sync_fkie/launch/master_sync.launch)

**Comment by sjoshi30** [comment]
Great, thank you for your response! It worked :)
