### ISSUE TITLE
Possible to use localhost for ROS and define an external IP?

### ISSUE THREAD

**Issue by AlexisTM** [fkie/multimaster_fkie#75]
I am willing to start the multimaster at boot, but the network (Zerotier VPN) is not ready so roscore fails.

The VPN conncets to the internet via a 4G module, meaning that it takes at least 1 minute to be "ready". 

I guess the master sync is using the ros master server directly, so it does not allow to use localhost to start and listen to/advertise another IP?

**Comment by atiderko** [comment]
Using _localhost_ for communication between master_sync and roscore is not the problem. But if you use _localhost_ in _ROS_MASTER_URI_ it can lead to problems in communication to remote ROS nodes.

Is it possible to delay start of ROS nodes until VPN es ready?

**Comment by AlexisTM** [comment]
The VPN is a "virtual interface" so the systemd triggers are not working; The network is not ready when the virtual device wakes up.

Which of the following solutions would be best: 
- Create a new FKIE application which first waits for the interface then run the main function of the original application
- Create an application that waits and returns when the interface has an IP, then run the normal roslaunch
- Isn't it possible to use `default_cfg_fkie` to run the next one once the first app returns?

**Comment by atiderko** [comment]
Does the ROS Master start if VPN is not ready?
If yes: it would be better to wait in the main function of FKIE application until VPN is ready.
if no: you need an external script or something else what trigger a roslaunch start after VPN is ready.

_default_cfg_fkie_ can delay a start of nodes or start these after a defined publisher topic is available.
Each node in roslauch needs follow parameter:
```
    <param name="default_cfg/autostart/required/publisher" value="topic_name" />
```

**Comment by AlexisTM** [comment]
No, the master will not start before the IP is set. I'll go for the script checking the interface and starting the roslaunch as soon as ready

**Comment by AlexisTM** [comment]
For future reference, this it the solution I chose:

Service file: `/lib/systemd/system/robot.service`

```bash
[Unit]
Description=Robot bringup for the universe app manager and multimaster 

[Service]
User=alexis
Group=alexis
ExecStart=/usr/share/bringup.sh

[Install]
WantedBy=multi-user.target
```

Bringup script: `/usr/share/bringup.sh`

```bash
#!/bin/bash

# Wait until zerotier network is ready using python one-liner
FOUND_IP=$(python -c "import socket; import fcntl; import struct; from time import sleep

def get_ip_address(ifname):
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    return socket.inet_ntoa(fcntl.ioctl(
        s.fileno(),
        0x8915,  # SIOCGIFADDR
        struct.pack('256s', ifname[:15])
    )[20:24])

while True:
  try:
    print get_ip_address('ztuzethfie')
    break
  except: 
    sleep(0.1)")
# End of python

bash -c "source /home/alexis/rossetup.bash && ROS_IP=$FOUND_IP ROS_HOSTNAME=$FOUND_IP ROS_MASTER_URI=http://$FOUND_IP:11311 stdbuf -oL roslaunch umd_platform bringup_robot.launch"
```

**Comment by atiderko** [comment]
@AlexisTM thank you for sharing!
