### ISSUE TITLE
ROS topics not visible to two machines

### ISSUE THREAD

**Issue by JadBatmobile** [fkie/multimaster_fkie#78]
Hello, i have succesfully setup multiple ROS Masters (2 master on 2 machines, to start). 

I followed this documentation:
http://www.iri.upc.edu/files/scidoc/1607-Multi-master-ROS-systems.pdf

I can do a rosservice call /master_discovery/list_masters on both machines and the results are:

Computer 1:

masters: 
  - 
    name: "hallab-system-product-name"
    uri: "http://hallab-System-Product-Name:11311/"
    timestamp: 1533590140.92
    timestamp_local: 1533590140.92
    online: True
    discoverer_name: "/master_discovery"
    monitoruri: "http://localhost:11611"
  - 
    name: "192.168.1.14"
    uri: "http://192.168.1.14:11311/"
    timestamp: 1533590128.81
    timestamp_local: 1533590128.81
    online: True
    discoverer_name: "/master_discovery"
    monitoruri: "http://192.168.1.14:11611"

Computer 2:

masters: 
  - 
    name: "hallab-system-product-name"
    uri: "http://hallab-System-Product-Name:11311/"
    timestamp: 1533590140.92
    timestamp_local: 1533590140.92
    online: True
    discoverer_name: "/master_discovery"
    monitoruri: "http://192.168.1.11:11611"
  - 
    name: "192.168.1.14"
    uri: "http://192.168.1.14:11311/"
    timestamp: 1533590128.81
    timestamp_local: 1533590128.81
    online: True
    discoverer_name: "/master_discovery"
    monitoruri: "http://localhost:11611"

Now, i go to publish a topic /test on machine 1, so that when i do rostopic list:

/master_discovery/changes
/master_discovery/linkstats
/rosout
/rosout_agg
/test

But, doing rostopic list on machine 2 gives:

/master_discovery/changes
/master_discovery/linkstats
/rosout
/rosout_agg

But no /test....

What am i missing here?

**Comment by atiderko** [comment]
It seems you run only `master_discovery` node. To synchronize the nodes, topics and services you need to run also `master_sync` node.

**Comment by JadBatmobile** [comment]
Ok, so the issue was that having ROS_IP set on the publishing computer somehow caused the published topics not to be visible on the subscribing computer.

Now that i unset ROS_IP, i can see the topics. The problem now is that i can't echo the topic on the subscribing computer, even tho i can rostopic list and rostopic info. So i can communicate with the master on the other computer, but i can't read the data.

**Comment by JadBatmobile** [comment]
Ok, if finnally worked. I had to set the ROS_HOSTNAME to the ip addresses of each machine. and i had to make sure ROS_IP was not set.

To be honest, this does not make sense to me, but at least i can proceed. Any explanation>?

**Comment by JadBatmobile** [comment]
It is defined explicitly with IP, not localhost.

I am interested in being able to control a remote computer's nodes with the node manager GUI. More specifically, i want to be able to use the capabilities view on the nodes of the remote computer. I have yet been able to do so. 

How would i go about this?

**Comment by JadBatmobile** [comment]
I can launch the nodes remotely. Every time i launch a node it asks for username and password. this is an inconvenience, how can i provide the password so that it doesnt ask constantly. 
NOTE: i can ssh into my remote computer with no password cause i configured the known_hosts, but node_manager keeps asking :#

**Comment by atiderko** [comment]
this behaviour is also new for me.

I use paramiko to open ssh connection to remote hosts. By default the username specified in the [Host description panel](http://fkie.github.io/multimaster_fkie/chapter_usage/host_description_panel.html) is used. Try to set this name bevor launch the nodes on remote host.

**Comment by JadBatmobile** [comment]
okay, what if i want to hardcode the password into your source code? Can you point me to the code where i can do this

**Comment by JadBatmobile** [comment]
nevermind! sorry, when i select the correct username in the Host Description Panel, it stops asking for passwords

**Comment by atiderko** [comment]
no problem! I'm happy that it works :-)
