### ISSUE TITLE
while catkin making multimaster_fkie it gives some errors

### ISSUE THREAD

**Issue by sunil1349** [fkie/multimaster_fkie#91]
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
node_manager_fkie/CMakeFiles/TARGET.dir/build.make:65: recipe for target '/home/syslap-172/Desktop/nodegui_ws/devel/share/node_manager_fkie/DATE' failed
make[2]: *** [/home/syslap-172/Desktop/nodegui_ws/devel/share/node_manager_fkie/DATE] Error 128

**Comment by atiderko** [comment]
thank you for reporting!

It should be fixed.
